services:
  mysql:
    image: mysql:8.0
    container_name: aq_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/db_schema.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: aq_adminer
    depends_on:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "${HOST_ADMINER_PORT}:8080"

  metabase:
    image: metabase/metabase:latest
    container_name: aq_metabase
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${HOST_METABASE_PORT}:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data

volumes:
  mysql_data:
  metabase_data:


  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    container_name: aq_etl
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Exemplo DB_URL usando credenciais do mysql do compose
      - DB_URL=mysql+pymysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE?charset=utf8mb4
      - ETL_INTERVAL_MINUTES=60   # rode a cada 60 minutos; remova para rodar uma vez
    volumes:
      - ./:/app
